-- =============================================
-- GOLDSMITH LOAN SYSTEM - SQL SCHEMA
-- Run this in Supabase SQL Editor
-- =============================================

-- ============================================
-- 1. LOANS TABLE (লোন একাউন্ট)
-- প্রতিটি লোনের মাস্টার রেকর্ড
-- ============================================
CREATE TABLE IF NOT EXISTS loans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    iid INT GENERATED ALWAYS AS IDENTITY (START WITH 5001),
    user_id UUID DEFAULT auth.uid() REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,

    -- Customer Info
    name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    nid_number TEXT,
    photo_url TEXT,
    nid_photo_url TEXT,

    -- Loan Info
    loan_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    interest_rate NUMERIC(5,2) NOT NULL DEFAULT 3.00,  -- monthly %
    loan_date DATE NOT NULL DEFAULT CURRENT_DATE,
    loan_months INT NOT NULL DEFAULT 1,
    deposit_item TEXT,  -- জামানত (collateral)

    -- Status
    status TEXT DEFAULT 'active' CHECK (status IN ('active','closed')),
    closed_at TIMESTAMPTZ,
    remarks TEXT,

    CONSTRAINT unique_loan_iid UNIQUE (iid)
);

-- ============================================
-- 2. LOAN_TRANSACTIONS TABLE (লোন লেনদেন)
-- জমা/পেমেন্ট ট্র্যাক করবে
-- ============================================
CREATE TABLE IF NOT EXISTS loan_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    loan_id UUID NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
    user_id UUID DEFAULT auth.uid() REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,

    txn_date DATE NOT NULL DEFAULT CURRENT_DATE,
    txn_type TEXT NOT NULL CHECK (txn_type IN ('payment','adjustment')),
    amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    
    -- Calculated at time of transaction
    principal_before NUMERIC(15,2) DEFAULT 0,   -- বাকি আসল (জমার আগে)
    interest_accrued NUMERIC(15,2) DEFAULT 0,    -- সুদ (শেষ txn থেকে এখন পর্যন্ত)
    total_due NUMERIC(15,2) DEFAULT 0,           -- আসল + সুদ
    balance_after NUMERIC(15,2) DEFAULT 0,       -- জমার পর বাকি
    
    remarks TEXT,
    loan_transactions_sl bigint generated by default as identity not null
);

-- ============================================
-- 3. INDEXES
-- ============================================
CREATE INDEX idx_loans_user ON loans(user_id, created_at);
CREATE INDEX idx_loans_iid ON loans(iid);
CREATE INDEX idx_loans_mobile ON loans(mobile);
CREATE INDEX idx_loans_status ON loans(status);
CREATE INDEX idx_loan_txn_loan ON loan_transactions(loan_id, txn_date);

-- ============================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ============================================
ALTER TABLE loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE loan_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own loans" ON loans FOR ALL TO authenticated
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own loan_transactions" ON loan_transactions FOR ALL TO authenticated
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================
-- 5. STORAGE BUCKET (run separately if needed)
-- Bucket name: accounting_db_bucket (already exists)
-- Max file size: 199KB
-- ============================================
-- INSERT INTO storage.buckets (id, name, public, file_size_limit)
-- VALUES ('accounting_db_bucket', 'accounting_db_bucket', true, 203776)
-- ON CONFLICT (id) DO NOTHING;


